### ISSUE TITLE
Ragfair/fleamarket throws exception on "find" (clone of #12 ?)

### ISSUE THREAD

**Issue by OneOverNull** [TrustedSourceLeaks/LeakedServer#14]
When initially opening the ragfair the server throws an error.
I'm running server from git hash: 917a4812eec6f3b5f4df74c4bf88a520c44d9ec6
And client from git hash: 2c3fa5a03d109ac2a7f0e527b7643d83b486f220

This appears to be the same/similar issue as #12 

Server exception:
`
[AID4291254181022964610Vu][127.0.0.1] /client/ragfair/find
[ERROR] Server:0.12.6-R2
[ERROR] Trace:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:450:10)
    at Object.readFileSync (fs.js:360:35)
    at Object.read (z:\EmuTarkov\12.6_Beta\server\core\util\json.js:22:15)
    at TraderServer.getAssort (z:\EmuTarkov\12.6_Beta\server\src\classes\trader.js:102:59)
    at Object.getOffers (z:\EmuTarkov\12.6_Beta\server\src\classes\ragfair.js:139:54)
    at Object.searchRagfair (z:\EmuTarkov\12.6_Beta\server\src\responses\ragfair.js:4:72)
    at Router.getResponse (z:\EmuTarkov\12.6_Beta\server\core\server\router.js:36:44)
    at Server.sendResponse (z:\EmuTarkov\12.6_Beta\server\core\server\server.js:138:29)
    at Inflate.cb (z:\EmuTarkov\12.6_Beta\server\core\server\server.js:179:28)
    at Inflate.zlibBufferOnEnd (zlib.js:149:10) {
  code: 'ERR_INVALID_ARG_TYPE
`

**Comment by KeKTapeCanFixIt** [comment]
https://github.com/TrustedSourceLeaks/LeakedServer/blob/917a4812eec6f3b5f4df74c4bf88a520c44d9ec6/src/classes/move.js#L374

`getAssort` takes a `sessionID` as well as the `traderID`. Should fix this issue as well as #12

**Comment by OneOverNull** [comment]
Thanks @KeKTapeCanFixIt I've added a PR with the fix based on your suggestion
