### ISSUE TITLE
Taking Hideout production item broken

### ISSUE THREAD

**Issue by Dulcior** [TrustedSourceLeaks/LeakedServer#17]
As title says taking an item that is done being produced in hideout throws error.

Running server:(https://github.com/TrustedSourceLeaks/LeakedServer/commit/917a4812eec6f3b5f4df74c4bf88a520c44d9ec6)

```[ERROR] Server:0.12.6-R2
[ERROR] Trace:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:450:10)
    at Object.readFileSync (fs.js:360:35)
    at Object.read (D:\Jet\LeakedServer\core\util\json.js:22:15)
    at TraderServer.getAssort (D:\Jet\LeakedServer\src\classes\trader.js:102:59)
    at Object.addItem (D:\Jet\LeakedServer\src\classes\move.js:374:39)
    at Object.takeProduction [as HideoutTakeProduction] (D:\Jet\LeakedServer\src\classes\hideout.js:296:17)
    at ItemServer.handleRoutes (D:\Jet\LeakedServer\src\classes\item.js:23:50)
    at Object.handleRoutes [as /client/game/profile/items/moving] (D:\Jet\LeakedServer\src\responses\item.js:4:49)
    at Router.getResponse (D:\Jet\LeakedServer\core\server\router.js:36:44)
    at Server.sendResponse (D:\Jet\LeakedServer\core\server\server.js:138:29) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by OneOverNull** [comment]
It's possible the PR for #12 fixes this 
However, I have not tested this scenario
