### ISSUE TITLE
Barter with goods goes wrong with trader

### ISSUE THREAD

**Issue by DarkWarCN** [TrustedSourceLeaks/LeakedServer#18]
![_3MZ$QILB1`8KU33)%65_CE](https://user-images.githubusercontent.com/49423303/84230352-5b753d00-ab1e-11ea-8c11-f457e6faa6b4.png)

**Comment by wilmeryu** [comment]
[ERROR] Server:0.12.6-R2
[ERROR] Trace:
TypeError: questassort.getQuestStatus is not a function
    at TraderServer.getAssort (D:\UserData\Desktop\ET12.6\server\src\classes\trader.js:124:67)
    at Object.getAssort [as /client/trading/api/getTraderAssort/] (D:\UserData\Desktop\ET12.6\server\src\responses\trader.js:22:53)
    at Router.getResponse (D:\UserData\Desktop\ET12.6\server\core\server\router.js:40:53)
    at Server.sendResponse (D:\UserData\Desktop\ET12.6\server\core\server\server.js:138:29)
    at Inflate.cb (D:\UserData\Desktop\ET12.6\server\core\server\server.js:179:28)
    at Inflate.zlibBufferOnEnd (zlib.js:149:10)
    at Inflate.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
