### ISSUE TITLE
can't open flea market

### ISSUE THREAD

**Issue by wilmeryu** [TrustedSourceLeaks/LeakedServer#21]
[AID51135429931308746gAjr][127.0.0.1] /client/ragfair/find
ragfair
user/cache/assort_ragfair.json
{
  items: 'user/cache/items.json',
  quests: 'user/cache/quests.json',
  locations: 'user/cache/locations.json',
  languages: 'user/cache/languages.json',
  customization: 'user/cache/customization.json',
  hideout_areas: 'user/cache/hideout_areas.json',
  hideout_production: 'user/cache/hideout_production.json',
  hideout_scavcase: 'user/cache/hideout_scavcase.json',
  weather: 'user/cache/weather.json',
  templates: 'user/cache/templates.json',
  mods: 'user/cache/mods.json',
  ragfair_offers: 'user/cache/ragfair_offers.json',
  assort_54cb50c76803fa8b248b4571: 'user/cache/assort_54cb50c76803fa8b248b4571.json',
  assort_54cb57776803fa99248b456e: 'user/cache/assort_54cb57776803fa99248b456e.json',
  assort_579dc571d53a0658a154fbec: 'user/cache/assort_579dc571d53a0658a154fbec.json',
  customization_579dc571d53a0658a154fbec: 'user/cache/customization_579dc571d53a0658a154fbec.json',
  assort_58330581ace78e27b8b10cee: 'user/cache/assort_58330581ace78e27b8b10cee.json',
  assort_5935c25fb3acc3127c3d8cd9: 'user/cache/assort_5935c25fb3acc3127c3d8cd9.json',
  assort_5a7c2eca46aef81a7ca2145d: 'user/cache/assort_5a7c2eca46aef81a7ca2145d.json',
  assort_5ac3b934156ae10c4430e83c: 'user/cache/assort_5ac3b934156ae10c4430e83c.json',
  customization_5ac3b934156ae10c4430e83c: 'user/cache/customization_5ac3b934156ae10c4430e83c.json',
  assort_5c0647fdd443bc2504c2d371: 'user/cache/assort_5c0647fdd443bc2504c2d371.json',
  assort_ragfair: 'user/cache/assort_ragfair.json',
  locale_en: 'user/cache/locale_en.json',
  locale_fr: 'user/cache/locale_fr.json',
  locale_ge: 'user/cache/locale_ge.json',
  locale_ru: 'user/cache/locale_ru.json'
}
[ERROR] Server:0.12.6-R2
[ERROR] Trace:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:450:10)
    at Object.readFileSync (fs.js:360:35)
    at Object.readFileSync (D:\UserData\Desktop\LeakedServer-master\EmuTarkov-Server.exe:201:55)
    at Object.read (D:\UserData\Desktop\LeakedServer-master\core\util\json.js:22:15)
    at TraderServer.getAssort (D:\UserData\Desktop\LeakedServer-master\src\classes\trader.js:112:43)
    at Object.getOffers (D:\UserData\Desktop\LeakedServer-master\src\classes\ragfair.js:138:54)
    at Object.searchRagfair (D:\UserData\Desktop\LeakedServer-master\src\responses\ragfair.js:4:72)
    at Router.getResponse (D:\UserData\Desktop\LeakedServer-master\core\server\router.js:36:44)
    at Server.sendResponse (D:\UserData\Desktop\LeakedServer-master\core\server\server.js:138:29)
    at Inflate.cb (D:\UserData\Desktop\LeakedServer-master\core\server\server.js:179:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by trustedLeaks** [comment]
This has already been fixed.
Closing.
