### ISSUE TITLE
purchase balaclava_dev from fency goes wrong

### ISSUE THREAD

**Issue by DarkWarCN** [TrustedSourceLeaks/LeakedServer#24]
`[ERROR] Server:0.12.6-R2
[ERROR] Trace:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:450:10)
    at Object.readFileSync (fs.js:360:35)
    at Object.readFileSync (C:\Users\zhang\Downloads\LeakedServer\EmuTarkov-Server.exe:201:55)
    at Object.read (C:\Users\zhang\Downloads\LeakedServer\core\util\json.js:22:15)
    at TraderServer.getAssort (C:\Users\zhang\Downloads\LeakedServer\src\classes\trader.js:112:43)
    at Object.addItem (C:\Users\zhang\Downloads\LeakedServer\src\classes\move.js:374:39)
    at buyItem (C:\Users\zhang\Downloads\LeakedServer\src\classes\trade.js:14:19)
    at Object.confirmTrading [as TradingConfirm] (C:\Users\zhang\Downloads\LeakedServer\src\classes\trade.js:60:16)
    at ItemServer.handleRoutes (C:\Users\zhang\Downloads\LeakedServer\src\classes\item.js:23:50)
    at Object.handleRoutes [as /client/game/profile/items/moving] (C:\Users\zhang\Downloads\LeakedServer\src\responses\item.js:4:49) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by OneOverNull** [comment]
Think this is the same issue as #22 
I can purchase things from fence with the fix in PR #23
