### ISSUE TITLE
Report some bugs

### ISSUE THREAD

**Issue by jamfanli** [TrustedSourceLeaks/LeakedServer#8]
1. Some items cannot be sold.
Loots brought back from the battlefield cannot be sold to merchants. There is no red error message on the server, but you cannot receive money, and the item will not be removed from your warehouse.

2. Merchant’s item reset time will not count down when the time is over.
The time countdown is completely normal after entering the game for the first time. But when the first countdown ends, the timing stops, it will not be automatically cycled.

3. Black screen after successful evacuation. The server log is as follows, it seems that there is a problem with health recovery.

TypeError: Cannot read property 'Hydration' of undefined
    at HealthServer.saveHealth (D:\Escape From Tarkov Offline\Server\src\classes\health.js:119:37)
    at Object.saveProgress (D:\Escape From Tarkov Offline\Server\src\classes\offraid.js:292:31)
    at Object.saveProgress [as /raid/profile/save] (D:\Escape From Tarkov Offline\Server\src\responses\offraid.js:13:15)
    at Router.getResponse (D:\Escape From Tarkov Offline\Server\core\server\router.js:36:44)
    at Server.sendResponse (D:\Escape From Tarkov Offline\Server\core\server\server.js:138:29)
    at Inflate.cb (D:\Escape From Tarkov Offline\Server\core\server\server.js:201:28)
    at Inflate.zlibBufferOnEnd (zlib.js:149:10)
    at Inflate.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by trustedLeaks** [comment]
1. This is happening cause of mods, mostly Prospero mod and Sorata one(it's now updated and need to be used instead of old versions)

2. Timer restock time isn't implemented yet
